name: docker-production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  clone-repo:
    uses: actions/checkout@v2
    runs-on: ubuntu-runner
    steps:
      - name: github-clone
        run: 
