name: hello_world

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello-world
        run: echo "hello-world"
        shell: bash
  match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: match-cricket
        run: echo "docker install"

