name: GCP API Block Test

on:
  workflow_dispatch:

jobs:
  test-blocked-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Who am I (debug)
        run: gcloud auth list

      - name: Test GCP Access
        run: gcloud projects list
